services:
  ollama:
    build: ./dockerfile_ollama  
    image: dockerfile_ollama:v1
    container_name: local_ollama
    restart: always
    ports:
      - "11434:11434"
    networks:
      - local_network

  anythingllm:
    build: ./dockerfile_anythingllm
    image: local_anythingllm:v1
    container_name: local_anythingllm
    restart: always
    ports:
      - "3001:3001"
    networks:
      - local_network

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: d:\\anythingllm_storage
  ollama_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: d:\\ollama_storage

networks:
  local_network:
    driver: bridge